=== chirag876/PythonWorkSpace/DataScanner/acord130_V2013_09.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "acord130_V2013_09",
  "type": "object",
  "properties": {
    "Page_1": {
      "type": "object",
      "properties": {
        "DATE (MM/DD/YYYY)": {
          "type": "string"
        },
        "AGENCY NAME AND ADDRESS": {
          "type": "string"
        },
        "COMPANY": {
          "type": "string"
        },
        "UNDERWRITER": {
          "type": "string"
        },
        "APPLICANT NAME": {
          "type": "string"
        },
        "OFFICE PHONE": {
          "type": "string"
        },
        "MOBILE PHONE": {
          "type": "string"
        },
        "MAILING ADDRESS (including ZIP or Canadian Postal Code)": {
          "type": "string"
        },
        "YRS BUS": {
          "type": "string"
        },
        "SIC": {
          "type": "string"
        },
        "PRODUCER NAME": {
          "type": "string"
        },
        "NAICS": {
          "type": "string"
        },
        "NAME CS REPRESENTATIVE": {
          "type": "string"
        },
        "WEBSITE ADDRESS": {
          "type": "string"
        },
        "OFFICE PHONE (A/C, No Extra": {
          "type": "string"
        },
        "E-MAIL ADDRESS": {
          "type": "string"
        },
        "SOLE PROPRIETOR": {
          "type": "string"
        },
        "CORPORATION": {
          "type": "string"
        },
        "LLC": {
          "type": "string"
        },
        "TRUST": {
          "type": "string"
        },
        "UNINCORPORATED ASSOCIATION": {
          "type": "string"
        },
        "FAX (A/C, Not": {
          "type": "string"
        },
        "SUBCHAPTER - CORP": {
          "type": "string"
        },
        "PARTNERSHIP": {
          "type": "string"
        },
        "JOINT VENTURE": {
          "type": "string"
        },
        "OTHER": {
          "type": "string"
        },
        "BUREAU NAME CREDIT": {
          "type": "string"
        },
        "ID NUMBER": {
          "type": "string"
        },
        "CODE": {
          "type": "string"
        },
        "SUB CODE": {
          "type": "string"
        },
        "FEDERAL EMPLOYER ID NUMBER": {
          "type": "string"
        },
        "NCCI RISK ID NUMBER": {
          "type": "string"
        },
        "OTHER RATING BUREAU in OR STATE EMPLOYER REGISTRATION NUMBER": {
          "type": "string"
        },
        "AGENCY CUSTOMER ID": {
          "type": "string"
        },
        "STATUS OF SUBMISSION": {
          "type": "object",
          "properties": {
            "QUOTE": {
              "type": "string"
            },
            "ISSUE POLICY": {
              "type": "string"
            },
            "BOUND (Give date and/or attach copy)": {
              "type": "string"
            },
            "ASSIGNED RISK (Attach ACORD 133)": {
              "type": "string"
            }
          },
          "required": [
            
          ]
        },
        "BILLING / AUDIT INFORMATION": {
          "type": "object",
          "properties": {
            "BILLING PLAN": {
              "type": "object",
              "properties": {
                "AGENCY BILL": {
                  "type": "string"
                },
                "DIRECT BILL": {
                  "type": "string"
                }
              },
              "required": [
               
              ]
            },
            "PAYMENT PLAN": {
              "type": "object",
              "properties": {
                "ANNUAL": {
                  "type": "string"
                },
                "SEMI-ANNUAL": {
                  "type": "string"
                },
                "QUARTERLY": {
                  "type": "string"
                },
                "% DOWN": {
                  "type": "string"
                }
              },
              "required": [
                
              ]
            },
            "AUDIT": {
              "type": "object",
              "properties": {
                "AT EXPIRATION": {
                  "type": "string"
                },
                "SEMI-ANNUAL": {
                  "type": "string"
                },
                "QUARTERLY": {
                  "type": "string"
                },
                "MONTHLY": {
                  "type": "string"
                }
              },
              "required": [
                
              ]
            }
          },
          "required": [
            
          ]
        },
        "POLICY INFORMATION": {
          "type": "object",
          "properties": {
            "PROPOSED EFF DATE": {
              "type": "string"
            },
            "PROPOSED EXP DATE": {
              "type": "string"
            },
            "NORMAL ANNIVERSARY RATING DATE": {
              "type": "string"
            },
            "PARTICIPATING": {
              "type": "string"
            },
            "RETRO PLAN": {
              "type": "string"
            },
            "PART 1 - WORKERS COMPENSATION (States)": {
              "type": "string"
            },
            "PART 2 - EMPLOYER'S LIABILITY": {
              "type": "object",
              "properties": {
                "EACH ACCIDENT": {
                  "type": "string"
                },
                "DISEASE-POLICY LIMIT": {
                  "type": "string"
                },
                "DISEASE-EACH EMPLOYEE": {
                  "type": "string"
                }
              },
              "required": [
                
              ]
            },
            "PART 3 - OTHER STATES INS": {
              "type": "string"
            },
            "DEDUCTIBLES (N / A in WI)": {
              "type": "object",
              "properties": {
                "MEDICAL": {
                  "type": "string"
                },
                "INDEMNITY": {
                  "type": "string"
                }
              },
              "required": [
                
              ]
            },
            "AMOUNT / % (N / A in WI)": {
              "type": "string"
            },
            "OTHER COVERAGES": {
              "type": "object",
              "properties": {
                "U.S.L. & H.": {
                  "type": "string"
                },
                "VOLUNTARY COMP": {
                  "type": "string"
                },
                "FOREIGN COV": {
                  "type": "string"
                },
                "MANAGED CARE OPTION": {
                  "type": "string"
                }
              },
              "required": [
                
              ]
            },
            "DIVIDEND PLAN/SAFETY GROUP": {
              "type": "string"
            },
            "ADDITIONAL COMPANY INFORMATION": {
              "type": "string"
            },
            "SPECIFY ADDITIONAL COVERAGES / ENDORSEMENTS (Attach ACORD 101, Additional Remarks Schedule, if more space is required)": {
              "type": "string"
            }
          },
          "required": [
            
          ]
        },
        "table_data": {
          "type": "string"
        }
      },
      "required": [
        
      ]
    },
    "Page_2": {
      "type": "object",
      "properties": {
        "AGENCY CUSTOMER ID": {
          "type": "string"
        },
        "PREMIUM": {
          "type": "object",
          "properties": {
            "TOTAL ESTIMATED ANNUAL PREMIUM": {
              "type": "string"
            },
            "MINIMUMPREMIUM": {
              "type": "string"
            },
            "DEPOSIT PREMIUM": {
              "type": "string"
            }
          },
          "required": [
            
          ]
        },
        "RATING INFORMATION - STATE": {
          "type": "string"
        },
        "REMARKS (ACORD 101, Additional Remarks Schedule, may be attached if more space is required)": {
          "type": "string"
        },
        "table_data": {
          "type": "string"
        }
      },
      "required": [
        
      ]
    },
    "Page_3": {
      "type": "object",
      "properties": {
        "AGENCY CUSTOMER ID": {
          "type": "string"
        },
        "NATURE OF BUSINESS / DESCRIPTION OF OPERATIONS": {
          "type": "object",
          "properties": {
            "GIVE COMMENTS AND DESCRIPTIONS OF BUSINESS OPERATIONS AND PRODUCTS MANUFACTURING RAW MATERIALS PROCESSES PRODUCT EQUIPMENT CONTRACTOR TYPE OF WORK SUB-CONTRACTS MERCANTILE MERCHANDISE CUSTOMERS DELIVERIES SERVICE TYPE LOCATION FARM ACREAGE ANIMALS MACHINERY SUB-CONTRACTS": {
              "type": "string"
            }
          },
          "required": [
          ]
        },
        "table_data": {
          "type": "string"
        }
      },
      "required": [
        
      ]
    },
    "Page_4": {
      "type": "object",
      "properties": {
        "AGENCY CUSTOMER ID": {
          "type": "string"
        },
        "SIGNATURE": {
          "type": "object",
          "properties": {
            "Copy of the Notice of information Practices (Privacy) has been given to the applicant (Not required in all states contact your agent or broker for your state's requirements.)": {
              "type": "string"
            },
            "(Applicant's Initials)": {
              "type": "string"
            },
            "PRODUCER'S SIGNATURE": {
              "type": "string"
            },
            "NATIONAL PRODUCER NUMBER": {
              "type": "string"
            },
            "APPLICANT'S SIGNATURE (Must be Officer Owner or Partner)": {
              "type": "string"
            },
            "ACORD": {
              "type": "string"
            },
            "DATE": {
              "type": "string"
            }
          },
          "required": [
            
          ]
        },
        "table_data": {
          "type": "string"
        }
      },
      "required": [
        
      ]
    }
  },
  "required": [
   
  ]
}

=== chirag876/PythonWorkSpace/PythonDataScanner/acord130_V2013_09/schema/config.json
{
    "Page_1":{
        "DATE (MM/DD/YYYY)": "",
        "AGENCY NAME AND ADDRESS": "",
        "COMPANY": "",
        "UNDERWRITER": "",
        "APPLICANT NAME": "",
        "OFFICE PHONE": "",
        "MOBILE PHONE": "",
        "MAILING ADDRESS (including ZIP or Canadian Postal Code)": "",
        "YRS BUS": "",
        "SIC": "",
        "PRODUCER NAME": "",
        "NAICS": "",
        "NAME CS REPRESENTATIVE": "",
        "WEBSITE ADDRESS": "",
        "OFFICE PHONE (A/C, No Extra": "",
        "E-MAIL ADDRESS": "",
        "SOLE PROPRIETOR": "",
        "CORPORATION": "",
        "LLC": "",
        "TRUST": "",
        "UNINCORPORATED ASSOCIATION": "",
        "FAX (A/C, Not": "",
        "SUBCHAPTER - CORP": "",
        "PARTNERSHIP": "",
        "JOINT VENTURE": "",
        "OTHER": "",
        "BUREAU NAME CREDIT": "",
        "ID NUMBER": "",
        "CODE": "",
        "SUB CODE": "",
        "FEDERAL EMPLOYER ID NUMBER": "",
        "NCCI RISK ID NUMBER": "",
        "OTHER RATING BUREAU in OR STATE EMPLOYER REGISTRATION NUMBER": "",
        "AGENCY CUSTOMER ID": "",

        "STATUS OF SUBMISSION":{
            "QUOTE":"",
            "ISSUE POLICY":"",
            "BOUND (Give date and/or attach copy)":"",
            "ASSIGNED RISK (Attach ACORD 133)":""
        },
        "BILLING / AUDIT INFORMATION":{
                "BILLING PLAN":{
                    "AGENCY BILL":"",
                    "DIRECT BILL":""
                    },
                "PAYMENT PLAN":{
                    "ANNUAL":"",
                    "SEMI-ANNUAL":"",
                    "QUARTERLY":"",
                    "% DOWN":""
                    },
                "AUDIT":{
                    "AT EXPIRATION":"",
                    "SEMI-ANNUAL":"",
                    "QUARTERLY":"",
                    "MONTHLY":""

                }
            },
        "POLICY INFORMATION":{
            "PROPOSED EFF DATE":"",
            "PROPOSED EXP DATE":"",
            "NORMAL ANNIVERSARY RATING DATE":"",
            "PARTICIPATING":"",
            "RETRO PLAN":"", 
            "PART 1 - WORKERS COMPENSATION (States)":"",
            "PART 2 - EMPLOYER'S LIABILITY":{
                "EACH ACCIDENT":"",
                "DISEASE-POLICY LIMIT":"",
                "DISEASE-EACH EMPLOYEE":""
                            },
            "PART 3 - OTHER STATES INS":"",
            "DEDUCTIBLES (N / A in WI)":{
                "MEDICAL":"",
                "INDEMNITY":""
            },
            "AMOUNT / % (N / A in WI)":"",
            "OTHER COVERAGES":{
                "U.S.L. & H.":"",
                "VOLUNTARY COMP":"",
                "FOREIGN COV":"",
                "MANAGED CARE OPTION":""
            },
            "DIVIDEND PLAN/SAFETY GROUP":"",
            "ADDITIONAL COMPANY INFORMATION":"",
            "SPECIFY ADDITIONAL COVERAGES / ENDORSEMENTS (Attach ACORD 101, Additional Remarks Schedule, if more space is required)":""
        },

        "table_data":""

    },

    "Page_2":{
       "AGENCY CUSTOMER ID":"",
       "PREMIUM":{
        "TOTAL ESTIMATED ANNUAL PREMIUM": "",
        "MINIMUMPREMIUM": "",
        "DEPOSIT PREMIUM": ""
       },
       "RATING INFORMATION - STATE":"",
       "REMARKS (ACORD 101, Additional Remarks Schedule, may be attached if more space is required)":"",
       "table_data":""
    },

    "Page_3":{
        "AGENCY CUSTOMER ID":"",
        "NATURE OF BUSINESS / DESCRIPTION OF OPERATIONS":{
        "GIVE COMMENTS AND DESCRIPTIONS OF BUSINESS OPERATIONS AND PRODUCTS MANUFACTURING RAW MATERIALS PROCESSES PRODUCT EQUIPMENT CONTRACTOR TYPE OF WORK SUB-CONTRACTS MERCANTILE MERCHANDISE CUSTOMERS DELIVERIES SERVICE TYPE LOCATION FARM ACREAGE ANIMALS MACHINERY SUB-CONTRACTS": ""
        },
        "table_data":""
        }
    ,
    "Page_4":{
        "AGENCY CUSTOMER ID": "",
        "SIGNATURE":{
            "Copy of the Notice of information Practices (Privacy) has been given to the applicant (Not required in all states contact your agent or broker for your state's requirements.)": "",
            "(Applicant's Initials)": "",
            "PRODUCER'S SIGNATURE": "",
            "NATIONAL PRODUCER NUMBER": "",
            "APPLICANT'S SIGNATURE (Must be Officer Owner or Partner)": "",
            "ACORD": "",
            "DATE": ""
        },
        "table_data":""
    }
}
